### ISSUE TITLE
booking complete SMS

### ISSUE THREAD

**Issue by nicaprentice** [Teamworks-Executive-Suites/plutus#60]
Your booking for {{property_name}} has finished. Please leave a review here: https://app.bookteamworks.com/tripDetails?tripPassed={{trip_ref}}&property={{property_ref}}

https://console.twilio.com/us1/develop/sms/content-template-builder/template/HXc108402b7127a3e68eef3bfd9333313b

**Comment by PrenSJ2** [comment]
done
